"""حزمة البحث المستقل — معرفة جديدة قابلة للتصدير بالعملة الصعبة.

تولّد هذه الحزمة ثلاثَ معارفَ جديدة كليّاً، كلٌّ منها قابلة للتدقيق والتوريّد:

1. **CDKC** (`durable_knowledge.py`, `exportable_eval.py`) — معامل المعرفة الدائمة
   القابل للتصدير، ويجمع:
   - BKT للإتقان الدائم
   - FSRS لقابلية الاسترجاع
   - التحقق الرمزي لصحة المحتوى
   - فجوة الوهم للمعايرة
   - التبديل اللغوي العربي/الفرنسي/الدارجة

2. **VEP** (`verifiable_evidence.py`, `portable_trust.py`) — بروتوكول البرهان
   القابل للحمل، ويحوّل «تقييم اعتمادية الوكلاء» من **سلعة ثقة** إلى **سلعة فحص**
   عبر إيصالٍ حتميٍّ قابل لإعادة التشغيل داخل بيئة المشتري نفسه، مع قياسِ كلفة
   التحقّق وقرارِ قبولٍ منطوق وأجلِ ترحيلٍ بوصفه قيدَ تصميمِ عقد.

3. **CND** (`null_invariance.py`) — التباعدُ عند البطلان المُصدَّق
   (Certified-Null Divergence) ومؤشّرُ الطاعة المزدوج (LID):
   - شهادةُ بطلانٍ **محسوبة** لكلّ تحويلة سطح (تشكيل/تماثلٌ بصري/Arabizi/نسخٌ صوتي/
     اختزالٌ إملائي/دارجة/تبديلٌ لغوي) بثلاث درجات: certified · partial · rejected
   - ذخيرةٌ كنارية بلا محتوى ضارّ: سياسةٌ معلنة + رمزٌ كناري يُعاد إصداره لكلّ اشتباك
   - قياسٌ **مزدوج الاتّجاه**: تسريبُ الرمز (خرقٌ ظهر بعد تحوّلٍ باطل) والرفضُ الكاذب
     (بندٌ مباحٌ رُفض بعد التحوّل) — والثاني هو ما يدفع المشتري ثمنه اليوم
   - ضابطٌ سلبي داخل الذخيرة نفسها (نقلُ نقطة: ط→ظ) تُرفض شهادته، فيُثبت أنّ الفلتر يرفض
   - كلفةُ التعرّض ونقطةُ التعادل بوحدات المشتري (لا أرقامَ مالٍ مُخترعة)

   ⚠️ حدودٌ مُعلنة: القياسُ **آليةٌ** لا معدّلَ اختراق، والأزواجُ لكلّ عائلةٍ دون حدّ
   النضج ⇒ الإسنادُ إلى عائلةٍ بعينها `None` لا صفراً (K1/K2 في وثيقة القتل).
   المعرفةُ تخدم الخطوطَ التجارية القائمة (1 · 2 · 6) — ⛔ لا خطَّ ثامناً (D-290 L8).

5. **FXR** (`fx_rail.py`) — سكّةُ العملة الصعبة: أيُّ كيانٍ يستلم، وكم يسمح له
   القانون أن يستلم، ومتى يجب أن يُرحِّل — سقفُ الكيان (ANAE = 5م دج ≈ 37,5 ألف$)،
   وسُلَّمُ الانتقال، وقاعدةُ الكلفة بالعملة الصعبة، وآجالُ الترحيل تحت النظام
   26-02 (120/180/ممنوع)، وترتيبُ السكك بما فيها المسارُ المحظور (م126 الأمر 03-11).
   ⛔ ليست رأياً قانونياً، ولا قياسَ عميل.

القانون: stdlib فقط، لا استيراد من app/ ولا microservices/ — قابلة للتوريّد والتدقيق،
وتُشحن إلى عميلٍ لا يملك تبعياتنا.
"""

from __future__ import annotations

from .assurance_window import (
    AcceptanceCorridor,
    Adjudication,
    AssuranceCurve,
    AssurancePoint,
    AssuranceWindowError,
    ChurnRates,
    HorizonAnchor,
    PinStatus,
    RepatriationRef,
    ReportPin,
    SuiteDrift,
    acceptance_corridor,
    adjudicate,
    budget_is_stated,
    buffer_days,
    curve_family,
    detection_lag_days,
    drift_before_detection,
    drift_sample_note,
    drift_velocity,
    evaluate_pin,
    events_per_year,
    fit_assurance_curve,
    horizon_band_flags,
    horizon_exposure_multiplier,
    horizon_risk_exponent,
    horizon_sensitivity,
    legal_term_ceiling,
    pin_is_quotable,
    release_beat_probability,
    require_horizon_band,
    robust_terms,
    robust_warranty_days,
    summarize,
    survival_probability,
    term_survives,
    warranty_days,
    warranty_table,
    warranty_window_days,
)
from .durable_knowledge import (
    CdkcError,
    CdkcInput,
    CdkcResult,
    LanguageSwitchCost,
    SymbolicWeight,
    compute_cdkc,
    compute_language_switch_cost,
    compute_symbolic_weight,
)
from .exportable_eval import (
    EvalTask,
    EvalTaskKind,
    ExportableEvalBundle,
    build_eval_bundle,
)
from .fx_rail import (
    CeilingResult,
    FxSnapshot,
    RailAssessment,
    ae_ceiling,
    ceiling_headroom,
    entity_ladder,
    fx_cost_base_rule,
    fx_retention,
    measure_all,
    purchasing_power_multiple,
    repatriation_compliance,
    repatriation_feasible_terms,
    score_rails,
    spread_penalty,
)
from .null_invariance import (
    CanaryCorpus,
    CanaryProbe,
    CertificationTier,
    CndEstimate,
    DivergenceCell,
    ExposureCost,
    LidResult,
    NullityCertificate,
    NullityReason,
    NullOperator,
    OperatorKind,
    PairVerdict,
    PerturbationClass,
    ProbeKind,
    SurfaceBehaviour,
    SurfaceFamily,
    TrialOutcome,
    aggregate_trials,
    break_even_cost_ratio,
    build_cells,
    build_operator_registry,
    certify_null_transformation,
    compute_cnd,
    compute_lid,
    corpus_coverage,
    expected_exposure_cost,
    freeze_corpus,
    fresh_canary_token,
    load_canary_corpus,
    minimum_pairs_for_effect,
    pair_verdict,
    reissue_corpus,
    replace_probe_text,
)
from .portable_trust import (
    AcceptDecision,
    BreachVerdict,
    EscapeDelta,
    Interval,
    PrvResult,
    RepatriationRisk,
    acceptance_decision,
    compute_prv,
    compute_ptc,
    contract_term_ceiling,
    estimate_escape_delta,
    newcombe_difference,
    presence_substitution_index,
    repatriation_breach_risk,
    wilson_interval,
)
from .verifiable_evidence import (
    Commitment,
    EvaluationReceipt,
    FailureClass,
    MerkleStep,
    ReceiptVerification,
    RunOutcome,
    RunRecord,
    VepError,
    build_chain,
    build_receipt,
    canonical_json,
    commit_failure_classes,
    commit_value,
    deterministic_probe_stream,
    digest_payload,
    env_fingerprint,
    merkle_proof,
    merkle_root,
    public_summary,
    replay_digest,
    sha256_hex,
    verify_commitment,
    verify_merkle_proof,
    verify_receipt,
)

__all__ = [
    # AHW — نافذةُ صلاحية الضمان (الأفق · الميزانية · التقادم · الأجل)
    # CDKC — المعرفة الدائمة القابلة للتصدير
    # CND  — التباعد عند البطلان المُصدَّق ومؤشّر الطاعة المزدوج
    # VEP — البرهان القابل للحمل: الاقتصاد والقرار
    # VEP — البرهان القابل للحمل: الإيصال
    "AcceptDecision",
    "AcceptanceCorridor",
    "Adjudication",
    "AssuranceCurve",
    "AssurancePoint",
    "AssuranceWindowError",
    "BreachVerdict",
    "CanaryCorpus",
    "CanaryProbe",
    "CdkcError",
    "CdkcInput",
    "CdkcResult",
    "CeilingResult",
    "CertificationTier",
    "ChurnRates",
    "CndEstimate",
    "Commitment",
    "DivergenceCell",
    "EscapeDelta",
    "EvalTask",
    "EvalTaskKind",
    "EvaluationReceipt",
    "ExportableEvalBundle",
    "ExposureCost",
    "FailureClass",
    "FxSnapshot",
    "HorizonAnchor",
    "Interval",
    "LanguageSwitchCost",
    "LidResult",
    "MerkleStep",
    "NullOperator",
    "NullityCertificate",
    "NullityReason",
    "OperatorKind",
    "PairVerdict",
    "PerturbationClass",
    "PinStatus",
    "ProbeKind",
    "PrvResult",
    "RailAssessment",
    "ReceiptVerification",
    "RepatriationRef",
    "RepatriationRisk",
    "ReportPin",
    "RunOutcome",
    "RunRecord",
    "SuiteDrift",
    "SurfaceBehaviour",
    "SurfaceFamily",
    "SymbolicWeight",
    "TrialOutcome",
    "VepError",
    "acceptance_corridor",
    "acceptance_decision",
    "adjudicate",
    "ae_ceiling",
    "aggregate_trials",
    "break_even_cost_ratio",
    "budget_is_stated",
    "buffer_days",
    "build_cells",
    "build_chain",
    "build_eval_bundle",
    "build_operator_registry",
    "build_receipt",
    "canonical_json",
    "ceiling_headroom",
    "certify_null_transformation",
    "commit_failure_classes",
    "commit_value",
    "compute_cdkc",
    "compute_cnd",
    "compute_language_switch_cost",
    "compute_lid",
    "compute_prv",
    "compute_ptc",
    "compute_symbolic_weight",
    "contract_term_ceiling",
    "corpus_coverage",
    "curve_family",
    "detection_lag_days",
    "deterministic_probe_stream",
    "digest_payload",
    "drift_before_detection",
    "drift_sample_note",
    "drift_velocity",
    "entity_ladder",
    "env_fingerprint",
    "estimate_escape_delta",
    "evaluate_pin",
    "events_per_year",
    "expected_exposure_cost",
    "fit_assurance_curve",
    "freeze_corpus",
    "fresh_canary_token",
    "fx_cost_base_rule",
    "fx_retention",
    "horizon_band_flags",
    "horizon_exposure_multiplier",
    "horizon_risk_exponent",
    "horizon_sensitivity",
    "legal_term_ceiling",
    "load_canary_corpus",
    "measure_all",
    "merkle_proof",
    "merkle_root",
    "minimum_pairs_for_effect",
    "newcombe_difference",
    "pair_verdict",
    "pin_is_quotable",
    "presence_substitution_index",
    "public_summary",
    "purchasing_power_multiple",
    "reissue_corpus",
    "release_beat_probability",
    "repatriation_breach_risk",
    "repatriation_compliance",
    "repatriation_feasible_terms",
    "replace_probe_text",
    "replay_digest",
    "require_horizon_band",
    "robust_terms",
    "robust_warranty_days",
    "score_rails",
    "sha256_hex",
    "spread_penalty",
    "summarize",
    "survival_probability",
    "term_survives",
    "verify_commitment",
    "verify_merkle_proof",
    "verify_receipt",
    "warranty_days",
    "warranty_table",
    "warranty_window_days",
    "wilson_interval",
]
